// Domyślne kategorie używane tylko do jednorazowego zasilenia (seed) tabeli Category.
// Od tego momentu kategorie są przechowywane w bazie i zarządzane na stronie /ustawienia/kategorie.
export const DEFAULT_EXPENSE_CATEGORIES = [
  "Mieszkanie",
  "Telefon",
  "Rzeczy do mieszk.",
  "Home",
  "Paliwo",
  "Auto",
  "Ubery",
  "Jedzenie",
  "Picie",
  "FastFood/Restauracje",
  "Barber",
  "Ubrania",
  "Kosmetyki",
  "Suple",
  "Sporty",
  "Edukacja/Ksiązki",
  "Alko",
  "Subskrybcje",
  "Pomaganie",
  "Wyjazdy",
  "Prezenty",
  "Inne",
  "Nala",
  "Hazard",
  "Zdrowie",
  "Rozrywka",
  "LEGO",
  "Akcesoria",
  "Delegacja",
  "Rower",
  "Narzędzia",
  "Elektronika",
] as const;

export const DEFAULT_INCOME_CATEGORIES = [
  "Wypłata",
  "Premia",
  "Delegacja",
  "Prezenty",
  "Hazard",
  "Odsetki",
  "Inne",
] as const;

export const MONTH_NAMES = [
  "Styczeń",
  "Luty",
  "Marzec",
  "Kwiecień",
  "Maj",
  "Czerwiec",
  "Lipiec",
  "Sierpień",
  "Wrzesień",
  "Październik",
  "Listopad",
  "Grudzień",
] as const;
